config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  get '/dashboard' => 'welcome#dashboard', as: :user_root
  resources :events
  resources :organizers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_organizers
  has_many :organizers, through: :event_organizers, source: :organizer
end

app/models/event_organizer.rb
class EventOrganizer < ApplicationRecord
  belongs_to :event
  belongs_to :organizer
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  has_many :event_organizers
  has_many :events, :through => :event_organizers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :start_date, :end_date, :intended_audience, :number_seats)
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index; end

  def dashboard; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
    
    <% @events.each do |event| %>
    <div class="col-md-4 col-sm-12 col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading"><%=event.name %></div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">Location :<%=event.location %></li>
                    <li class="list-group-item">Start date:<%=event.start_date %></li>  
                    <li class="list-group-item">End date: <%=event.end_date %></li> 
                    <li class="list-group-item">Itended audience: <%=event.intended_audience %></li> 
                    <li class="list-group-item">Number of Seats: <span class="badge"><%=event.number_seats %></span></li>    
                </ul> 
            </div>
            <div class="panel-footer">
                <button class="btn btn-info">
                    Details
                </button>

                  <button class="btn btn-danger">
                    Delete
                </button>
            </div>
        </div>
        </div>
    <% end %>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Eventnest" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Eventnest</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Events", events_path  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
           <li><%= link_to "Profile", edit_user_registration_path  %></li>
            <li><%= link_to "Logout", destroy_user_session_path,method: :delete %></li>
            <% else %>
            <li><%= link_to "Login", new_user_session_path  %></li>
            <li><%= link_to "Sign up", new_user_registration_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
       
          <%= bootstrap_flash %>
          <%= yield %>
      
      </div><!--/row-->

      <footer>
      <div class="container">
        <p>&copy; Company 2020</p>
      </div>
      
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/dashboard.html.erb
  <div class="jumbotron">
    <h1>Dashboard</h1>
    
  </div>
  </div>

app/views/welcome/index.html.erb
  <div class="jumbotron">
    <h1>Welcome to EventNest</h1>
    <p>Please Login or sign up</p>
  </div>
  </div>